version: "3"

services:
  app:
    image: sinashk/tlswebsite
    restart: always
    expose:
      - 8080
    environment:
      ADDR: ":8080"
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
