version: "3"

services:
  app:
    image: sinashk/tlswebsite
    restart: always
    expose:
      - 8080
    environment:
      ADDR: ":8080"
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - 80
      - 443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
    depends_on:
      - app
